### ISSUE TITLE
Segmentation fault (core dumped) due to GUI 

### ISSUE THREAD

**Issue by ibrahimhroob** [azaganidis/se_ndt#12]
Hi Anestis, 

I was able to compile the code, thanks to #11 , but when I was trying to run the code I got segmentation fault
`ibrahim@ih:~/se_ndt/build$ ./kitti_slam -p /media/ibrahim/ibrahim/velodyne/* -l /media/ibrahim/ibrahim/predictions/* -v`
`win_run`
`Segmentation fault (core dumped)`

I got this after pressing any key on the keyboard, any idea how I can debug it? 

Note I am on ubuntu 18.04 + I built the project with the debug option " cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_GL=True .."

Thanks

**Comment by ibrahimhroob** [comment]
@azaganidis , which version of ceres-solver did you use? thanks

**Comment by ibrahimhroob** [comment]
Hi, I was able to get some useful debugging messages using clion, this what I got:

> WARNING: Logging before InitGoogleLogging() is written to STDERR
F1213 15:08:02.477965 17716 problem_impl.cc:635] Parameter block not found: 0x563835922260. You must add the parameter block to the problem before it can be set constant.

**Comment by azaganidis** [comment]
I have Ceres 1.14.0. I haven't seen this error before.
I am setting a parameter block to constant only here, so you could try to comment this out and see if it still segfaults.
https://github.com/azaganidis/se_ndt/blob/6d9cdb99992f3422f425088f61fe9749411fb759/src/pose_graph_3d.cc#L60
However, if this happens when you press a key then it is probably from OpenGL, I would try to debug that with gdb. 
You could also un-comment this line https://github.com/azaganidis/se_ndt/blob/6d9cdb99992f3422f425088f61fe9749411fb759/src/kitti_slam.cpp#L122 to see on the terminal if it is processing frames and the failure is from the GUI.

**Comment by ibrahimhroob** [comment]
Thanks for your reply, I think I was able to debug it using gdb, here what I got: 
>Thread 5 "kitti_slam" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffeee3c700 (LWP 20372)]
0x00007ffff5c576e9 in glLoadIdentity ()
   from /usr/lib/x86_64-linux-gnu/libGL.so.1

hmm, it seems this is from OpenGL then, any idea how this could be worked around?

**Comment by ibrahimhroob** [comment]
Hi @azaganidis , I am closing this issue as this is appears to be an issue with NVIDIA drivers, so we changed the display drivers to the open source one, which seems to work and it does not crash now on glLoadIdentity() ... thanks
